// Client-side app logic. Kept as plain string concatenation (no template
// literals) because this whole file is itself embedded inside a TS template
// literal by ui/page.ts -- avoiding backticks here avoids escaping headaches.
export const CLIENT_SCRIPT = [
'var audio = document.getElementById("audio-player");',
'var $ = function (id) { return document.getElementById(id); };',
'var state = {',
'  user: null,',
'  tracks: [],',
'  playlists: [],',
'  queue: [],',
'  currentIndex: -1,',
'  shuffle: false,',
'  repeat: false,',
'  view: "home-view",',
'  libraryTab: "tracks",',
'  activePlaylistId: null,',
'  search: ""',
'};',

'function formatTime(value) {',
'  if (!isFinite(value) || value < 0) return "0:00";',
'  var total = Math.floor(value);',
'  var minutes = Math.floor(total / 60);',
'  var seconds = String(total % 60).padStart(2, "0");',
'  return minutes + ":" + seconds;',
'}',

'function setText(id, value) { $(id).textContent = value || ""; }',
'function trackArtist(t) { return t.artist || "Unknown Artist"; }',
'function trackAlbum(t) { return t.album || "Unknown Album"; }',

'var toastTimer = null;',
'function toast(message) {',
'  var el = $("toast");',
'  el.textContent = message;',
'  el.classList.add("show");',
'  clearTimeout(toastTimer);',
'  toastTimer = setTimeout(function () { el.classList.remove("show"); }, 2600);',
'}',

'function coverImg(className, url, size) {',
'  var span = document.createElement("span");',
'  span.className = className;',
'  if (url) {',
'    var img = document.createElement("img");',
'    img.src = url;',
'    img.loading = "lazy";',
'    img.alt = "";',
'    span.appendChild(img);',
'  } else {',
'    span.innerHTML = ICONS.music;',
'  }',
'  return span;',
'}',

'function renderTrackRow(track, index, opts) {',
'  opts = opts || {};',
'  var row = document.createElement("button");',
'  row.className = "track-row" + (index === state.currentIndex && opts.list === state.activeListId ? " playing" : "");',
'  row.type = "button";',

'  row.appendChild(coverImg("track-thumb", track.cover_url));',

'  var info = document.createElement("span");',
'  info.className = "track-info";',
'  var title = document.createElement("span");',
'  title.className = "track-name";',
'  title.textContent = track.title || "Untitled";',
'  var meta = document.createElement("span");',
'  meta.className = "track-meta";',
'  meta.textContent = trackArtist(track) + " \u2014 " + trackAlbum(track);',
'  info.appendChild(title);',
'  info.appendChild(meta);',
'  row.appendChild(info);',

'  var more = document.createElement("span");',
'  more.className = "track-more";',
'  more.innerHTML = ICONS.more;',
'  row.appendChild(more);',

'  row.addEventListener("click", function (e) {',
'    if (e.target.closest(".track-more")) {',
'      e.stopPropagation();',
'      openTrackMenu(track);',
'      return;',
'    }',
'    if (opts.onPlay) opts.onPlay(); else playFromLibrary(index);',
'  });',
'  return row;',
'}',

'function playFromLibrary(index) {',
'  state.queue = state.tracks;',
'  state.activeListId = "library";',
'  playTrack(index);',
'}',

'function renderLists() {',
'  var recent = $("recent-list");',
'  var library = $("library-list");',
'  recent.replaceChildren();',
'  library.replaceChildren();',

'  var filtered = state.tracks;',
'  if (!filtered.length) {',
'    library.appendChild(emptyState("music", "\u0411\u0438\u0431\u043b\u0438\u043e\u0442\u0435\u043a\u0430 \u043f\u043e\u043a\u0430 \u043f\u0443\u0441\u0442\u0430"));',
'    recent.appendChild(emptyState("music", "\u041d\u0435\u0447\u0435\u0433\u043e \u0441\u043b\u0443\u0448\u0430\u0442\u044c"));',
'    return;',
'  }',

'  filtered.forEach(function (track, index) {',
'    library.appendChild(renderTrackRow(track, index, { list: "library" }));',
'  });',

'  filtered.slice(0, 6).forEach(function (track) {',
'    var index = state.tracks.indexOf(track);',
'    recent.appendChild(renderTrackRow(track, index, { list: "library" }));',
'  });',
'}',

'function emptyState(iconName, text) {',
'  var wrap = document.createElement("div");',
'  wrap.className = "empty";',
'  var icon = document.createElement("div");',
'  icon.innerHTML = ICONS[iconName] || ICONS.music;',
'  icon.style.display = "flex";',
'  icon.style.justifyContent = "center";',
'  wrap.appendChild(icon);',
'  var p = document.createElement("div");',
'  p.textContent = text;',
'  wrap.appendChild(p);',
'  return wrap;',
'}',

'function updateNowPlaying() {',
'  var track = state.queue[state.currentIndex];',
'  var hasTrack = Boolean(track);',

'  $("mini-player").classList.toggle("hidden", !hasTrack);',
'  if (!hasTrack) {',
'    setText("hero-title", "\u041d\u0438\u0447\u0435\u0433\u043e \u043d\u0435 \u0438\u0433\u0440\u0430\u0435\u0442");',
'    setText("hero-subtitle", "\u0412\u044b\u0431\u0435\u0440\u0438 \u0442\u0440\u0435\u043a \u0438\u0437 \u0431\u0438\u0431\u043b\u0438\u043e\u0442\u0435\u043a\u0438");',
'    $("hero-art").replaceChildren();',
'    $("hero-art").innerHTML = ICONS.music;',
'    return;',
'  }',

'  var title = track.title || "Untitled";',
'  var subtitle = trackArtist(track) + " \u2014 " + trackAlbum(track);',

'  setText("hero-title", title);',
'  setText("hero-subtitle", subtitle);',
'  setText("mini-title", title);',
'  setText("mini-artist", subtitle);',

'  var heroArt = $("hero-art");',
'  heroArt.replaceChildren();',
'  if (track.cover_url) {',
'    var img1 = document.createElement("img");',
'    img1.src = track.cover_url;',
'    img1.alt = "";',
'    heroArt.appendChild(img1);',
'  } else {',
'    heroArt.innerHTML = ICONS.music;',
'  }',

'  var miniArt = $("mini-art");',
'  miniArt.replaceChildren();',
'  if (track.cover_url) {',
'    var img2 = document.createElement("img");',
'    img2.src = track.cover_url;',
'    img2.alt = "";',
'    miniArt.appendChild(img2);',
'  }',

'  $("play-button").innerHTML = audio.paused ? ICONS.play : ICONS.pause;',
'  $("mini-play").innerHTML = audio.paused ? ICONS.play : ICONS.pause;',
'  var pct = audio.duration ? (audio.currentTime / audio.duration) * 100 : 0;',
'  $("progress").value = audio.duration ? Math.round((audio.currentTime / audio.duration) * 1000) : 0;',
'  $("mini-progress-fill").style.width = pct + "%";',
'  setText("current-time", formatTime(audio.currentTime));',
'  setText("total-time", formatTime(audio.duration));',

'  if ("mediaSession" in navigator) {',
'    navigator.mediaSession.metadata = new MediaMetadata({',
'      title: title,',
'      artist: trackArtist(track),',
'      album: trackAlbum(track),',
'      artwork: track.cover_url ? [',
'        { src: track.cover_url, sizes: "512x512", type: "image/jpeg" }',
'      ] : []',
'    });',
'    navigator.mediaSession.playbackState = audio.paused ? "paused" : "playing";',
'  }',
'}',

'function setupMediaSession() {',
'  if (!("mediaSession" in navigator)) return;',
'  navigator.mediaSession.setActionHandler("play", togglePlay);',
'  navigator.mediaSession.setActionHandler("pause", togglePlay);',
'  navigator.mediaSession.setActionHandler("previoustrack", previousTrack);',
'  navigator.mediaSession.setActionHandler("nexttrack", nextTrack);',
'  navigator.mediaSession.setActionHandler("seekto", function (details) {',
'    if (details.seekTime != null && audio.duration) audio.currentTime = details.seekTime;',
'  });',
'}',

'async function playTrack(index) {',
'  if (!state.queue[index]) return;',
'  state.currentIndex = index;',
'  var track = state.queue[index];',
'  audio.src = "/api/tracks/" + encodeURIComponent(track.id) + "/stream";',
'  updateNowPlaying();',
'  try { await audio.play(); } catch (e) { /* Safari may block autoplay */ }',
'  updateNowPlaying();',
'}',

'async function togglePlay() {',
'  if (state.currentIndex < 0 && state.queue.length) { await playTrack(0); return; }',
'  if (audio.paused) { try { await audio.play(); } catch (e) {} }',
'  else { audio.pause(); }',
'  updateNowPlaying();',
'}',

'function nextTrack() {',
'  if (!state.queue.length) return;',
'  if (state.shuffle && state.queue.length > 1) {',
'    var next;',
'    do { next = Math.floor(Math.random() * state.queue.length); } while (next === state.currentIndex);',
'    playTrack(next);',
'    return;',
'  }',
'  var next2 = state.currentIndex + 1;',
'  if (next2 < state.queue.length) playTrack(next2);',
'  else if (state.repeat) playTrack(0);',
'}',

'function previousTrack() {',
'  if (audio.currentTime > 3) { audio.currentTime = 0; return; }',
'  var prev = state.currentIndex - 1;',
'  if (prev >= 0) playTrack(prev);',
'}',

'function switchView(viewId) {',
'  state.view = viewId;',
'  ["home-view", "library-view", "search-view", "profile-view"].forEach(function (id) {',
'    $(id).classList.toggle("hidden", id !== viewId);',
'  });',
'  document.querySelectorAll(".nav-button").forEach(function (btn) {',
'    btn.classList.toggle("active", btn.dataset.view === viewId);',
'  });',
'  window.scrollTo(0, 0);',
'}',

'async function checkAuth() {',
'  try {',
'    var res = await fetch("/api/auth/me");',
'    if (!res.ok) throw new Error();',
'    var data = await res.json();',
'    state.user = data.user;',
'    showApp();',
'  } catch (e) { showLogin(); }',
'}',

'function showLogin() {',
'  $("login-screen").classList.remove("hidden");',
'  $("app-screen").classList.add("hidden");',
'  $("bottom-nav").classList.add("hidden");',
'  $("mini-player").classList.add("hidden");',
'}',

'function showApp() {',
'  $("login-screen").classList.add("hidden");',
'  $("app-screen").classList.remove("hidden");',
'  $("bottom-nav").classList.remove("hidden");',
'  setText("user-initial", (state.user.username || "?").slice(0, 1).toUpperCase());',
'  setText("profile-name", state.user.username);',
'  setText("profile-role", state.user.role === "admin" ? "\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440" : "\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c");',
'  setText("profile-initial", (state.user.username || "?").slice(0, 1).toUpperCase());',
'  $("admin-section").classList.toggle("hidden", state.user.role !== "admin");',
'  loadTracks();',
'  loadPlaylists();',
'  if (state.user.role === "admin") loadUsers();',
'}',

'async function loadTracks() {',
'  try {',
'    var res = await fetch("/api/tracks");',
'    if (!res.ok) return;',
'    var data = await res.json();',
'    state.tracks = data.tracks || [];',
'    if (state.activeListId === "library" && state.currentIndex >= state.queue.length) {',
'      state.currentIndex = -1;',
'      audio.pause();',
'      audio.removeAttribute("src");',
'      audio.load();',
'    }',
'    renderLists();',
'    updateNowPlaying();',
'  } catch (e) { /* keep current UI on network blip */ }',
'}',

'/* ---------- Playlists ---------- */',
'async function loadPlaylists() {',
'  try {',
'    var res = await fetch("/api/playlists");',
'    if (!res.ok) return;',
'    var data = await res.json();',
'    state.playlists = data.playlists || [];',
'    renderPlaylists();',
'  } catch (e) {}',
'}',

'function renderPlaylists() {',
'  var container = $("playlists-list");',
'  container.replaceChildren();',
'  if (!state.playlists.length) {',
'    container.appendChild(emptyState("playlist", "\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442\u043e\u0432 \u043f\u043e\u043a\u0430 \u043d\u0435\u0442"));',
'    return;',
'  }',
'  state.playlists.forEach(function (pl) {',
'    var row = document.createElement("button");',
'    row.className = "track-row";',
'    row.type = "button";',
'    var thumb = document.createElement("span");',
'    thumb.className = "track-thumb";',
'    thumb.innerHTML = ICONS.playlist;',
'    row.appendChild(thumb);',
'    var info = document.createElement("span");',
'    info.className = "track-info";',
'    var title = document.createElement("span");',
'    title.className = "track-name";',
'    title.textContent = pl.name;',
'    var meta = document.createElement("span");',
'    meta.className = "track-meta";',
'    meta.textContent = pl.track_count + " \u0442\u0440\u0435\u043a\u043e\u0432";',
'    info.appendChild(title);',
'    info.appendChild(meta);',
'    row.appendChild(info);',
'    row.addEventListener("click", function () { openPlaylist(pl.id); });',
'    container.appendChild(row);',
'  });',
'}',

'async function openPlaylist(id) {',
'  var res = await fetch("/api/playlists/" + encodeURIComponent(id));',
'  if (!res.ok) return;',
'  var data = await res.json();',
'  state.activePlaylistId = id;',
'  setText("playlist-detail-title", data.playlist.name);',
'  var list = $("playlist-detail-list");',
'  list.replaceChildren();',
'  if (!data.tracks.length) {',
'    list.appendChild(emptyState("music", "\u0412 \u044d\u0442\u043e\u043c \u043f\u043b\u0435\u0439\u043b\u0438\u0441\u0442\u0435 \u043f\u043e\u043a\u0430 \u043f\u0443\u0441\u0442\u043e"));',
'  } else {',
'    data.tracks.forEach(function (track, index) {',
'      list.appendChild(renderTrackRow(track, index, {',
'        list: "playlist",',
'        onPlay: function () {',
'          state.queue = data.tracks;',
'          state.activeListId = "playlist";',
'          playTrack(index);',
'        }',
'      }));',
'    });',
'  }',
'  $("playlist-list-view").classList.add("hidden");',
'  $("playlist-detail-view").classList.remove("hidden");',
'}',

'$("playlist-back").addEventListener("click", function () {',
'  $("playlist-detail-view").classList.add("hidden");',
'  $("playlist-list-view").classList.remove("hidden");',
'  loadPlaylists();',
'});',

'$("create-playlist-form").addEventListener("submit", async function (e) {',
'  e.preventDefault();',
'  var name = $("new-playlist-name").value.trim();',
'  if (!name) return;',
'  var res = await fetch("/api/playlists", {',
'    method: "POST",',
'    headers: { "Content-Type": "application/json" },',
'    body: JSON.stringify({ name: name })',
'  });',
'  if (res.ok) {',
'    $("create-playlist-form").reset();',
'    $("new-playlist-modal").classList.add("hidden");',
'    loadPlaylists();',
'  } else {',
'    toast("\u041e\u0448\u0438\u0431\u043a\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u043f\u043b\u0435\u0439\u043b\u0438\u0441\u0442\u0430");',
'  }',
'});',

'$("new-playlist-button").addEventListener("click", function () {',
'  $("new-playlist-modal").classList.remove("hidden");',
'  $("new-playlist-name").focus();',
'});',
'$("new-playlist-cancel").addEventListener("click", function () {',
'  $("new-playlist-modal").classList.add("hidden");',
'});',

'/* ---------- Track menu (add to playlist / edit / delete) ---------- */',
'var menuTrack = null;',
'function openTrackMenu(track) {',
'  menuTrack = track;',
'  var list = $("track-menu-list");',
'  list.replaceChildren();',

'  var addItem = document.createElement("button");',
'  addItem.className = "modal-list-item";',
'  addItem.innerHTML = ICONS.playlist + "<span style=\\"margin-left:10px;flex:1\\">\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0432 \u043f\u043b\u0435\u0439\u043b\u0438\u0441\u0442</span>";',
'  addItem.addEventListener("click", function () { closeTrackMenu(); openAddToPlaylist(track); });',
'  list.appendChild(addItem);',

'  var delItem = document.createElement("button");',
'  delItem.className = "modal-list-item";',
'  delItem.style.color = "#ff6961";',
'  delItem.innerHTML = ICONS.trash + "<span style=\\"margin-left:10px;flex:1\\">\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0442\u0440\u0435\u043a</span>";',
'  delItem.addEventListener("click", async function () {',
'    closeTrackMenu();',
'    if (!confirm("\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u00ab" + track.title + "\u00bb?")) return;',
'    var res = await fetch("/api/tracks/" + encodeURIComponent(track.id), { method: "DELETE" });',
'    if (res.ok) { toast("\u0422\u0440\u0435\u043a \u0443\u0434\u0430\u043b\u0451\u043d"); loadTracks(); }',
'    else toast("\u041e\u0448\u0438\u0431\u043a\u0430 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f");',
'  });',
'  list.appendChild(delItem);',

'  setText("track-menu-title", track.title || "Untitled");',
'  $("track-menu-modal").classList.remove("hidden");',
'}',
'function closeTrackMenu() { $("track-menu-modal").classList.add("hidden"); }',
'$("track-menu-backdrop").addEventListener("click", closeTrackMenu);',

'async function openAddToPlaylist(track) {',
'  if (!state.playlists.length) { toast("\u0421\u043d\u0430\u0447\u0430\u043b\u0430 \u0441\u043e\u0437\u0434\u0430\u0439 \u043f\u043b\u0435\u0439\u043b\u0438\u0441\u0442"); return; }',
'  var list = $("add-to-playlist-list");',
'  list.replaceChildren();',
'  state.playlists.forEach(function (pl) {',
'    var item = document.createElement("button");',
'    item.className = "modal-list-item";',
'    item.textContent = pl.name;',
'    item.addEventListener("click", async function () {',
'      var res = await fetch("/api/playlists/" + encodeURIComponent(pl.id) + "/tracks", {',
'        method: "POST",',
'        headers: { "Content-Type": "application/json" },',
'        body: JSON.stringify({ track_id: track.id })',
'      });',
'      $("add-to-playlist-modal").classList.add("hidden");',
'      if (res.ok) toast("\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u043e \u0432 \u00ab" + pl.name + "\u00bb");',
'      else toast("\u041e\u0448\u0438\u0431\u043a\u0430");',
'    });',
'    list.appendChild(item);',
'  });',
'  $("add-to-playlist-modal").classList.remove("hidden");',
'}',
'$("add-to-playlist-backdrop").addEventListener("click", function () {',
'  $("add-to-playlist-modal").classList.add("hidden");',
'});',

'/* ---------- Search ---------- */',
'$("search-input").addEventListener("input", function () {',
'  state.search = this.value.trim().toLowerCase();',
'  renderSearch();',
'});',

'function renderSearch() {',
'  var results = $("search-results");',
'  results.replaceChildren();',
'  if (!state.search) {',
'    results.appendChild(emptyState("search", "\u041d\u0430\u0439\u0434\u0438 \u0442\u0440\u0435\u043a, \u0438\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044f \u0438\u043b\u0438 \u0430\u043b\u044c\u0431\u043e\u043c"));',
'    return;',
'  }',
'  var matches = state.tracks.filter(function (t) {',
'    var hay = (t.title + " " + trackArtist(t) + " " + trackAlbum(t)).toLowerCase();',
'    return hay.indexOf(state.search) !== -1;',
'  });',
'  if (!matches.length) {',
'    results.appendChild(emptyState("search", "\u041d\u0438\u0447\u0435\u0433\u043e \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u043e"));',
'    return;',
'  }',
'  matches.forEach(function (track) {',
'    var index = state.tracks.indexOf(track);',
'    results.appendChild(renderTrackRow(track, index, {',
'      list: "library",',
'      onPlay: function () { playFromLibrary(index); }',
'    }));',
'  });',
'}',

'/* ---------- Login / logout ---------- */',
'$("login-form").addEventListener("submit", async function (e) {',
'  e.preventDefault();',
'  var username = $("login-username").value.trim();',
'  var password = $("login-password").value;',
'  $("login-error").classList.add("hidden");',
'  try {',
'    var res = await fetch("/api/auth/login", {',
'      method: "POST",',
'      headers: { "Content-Type": "application/json" },',
'      body: JSON.stringify({ username: username, password: password })',
'    });',
'    if (!res.ok) {',
'      var data = await res.json().catch(function () { return {}; });',
'      setText("login-error", data.error || "\u041e\u0448\u0438\u0431\u043a\u0430 \u0432\u0445\u043e\u0434\u0430");',
'      $("login-error").classList.remove("hidden");',
'      return;',
'    }',
'    await checkAuth();',
'  } catch (e) {',
'    setText("login-error", "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0438\u0442\u044c\u0441\u044f \u043a \u0441\u0435\u0440\u0432\u0435\u0440\u0443");',
'    $("login-error").classList.remove("hidden");',
'  }',
'});',

'async function logout() {',
'  await fetch("/api/auth/logout", { method: "POST" }).catch(function () {});',
'  state.user = null;',
'  state.tracks = [];',
'  state.currentIndex = -1;',
'  audio.pause();',
'  audio.removeAttribute("src");',
'  audio.load();',
'  showLogin();',
'}',
'$("logout-button").addEventListener("click", logout);',
'$("user-button").addEventListener("click", function () { switchView("profile-view"); });',

'$("play-button").addEventListener("click", togglePlay);',
'$("mini-play").addEventListener("click", togglePlay);',
'$("next-button").addEventListener("click", nextTrack);',
'$("mini-next").addEventListener("click", nextTrack);',
'$("prev-button").addEventListener("click", previousTrack);',

'$("shuffle-button").addEventListener("click", function () {',
'  state.shuffle = !state.shuffle;',
'  $("shuffle-button").classList.toggle("active", state.shuffle);',
'});',
'$("repeat-button").addEventListener("click", function () {',
'  state.repeat = !state.repeat;',
'  $("repeat-button").classList.toggle("active", state.repeat);',
'});',

'$("progress").addEventListener("input", function () {',
'  if (audio.duration) audio.currentTime = (Number($("progress").value) / 1000) * audio.duration;',
'});',

'$("mini-player").addEventListener("click", function (e) {',
'  if (e.target.closest("button")) return;',
'  switchView("home-view");',
'});',

'document.querySelectorAll(".nav-button").forEach(function (btn) {',
'  btn.addEventListener("click", function () { switchView(btn.dataset.view); });',
'});',

'document.querySelectorAll(".library-tab").forEach(function (btn) {',
'  btn.addEventListener("click", function () {',
'    state.libraryTab = btn.dataset.tab;',
'    document.querySelectorAll(".library-tab").forEach(function (b) { b.classList.toggle("active", b === btn); });',
'    $("library-tracks-panel").classList.toggle("hidden", btn.dataset.tab !== "tracks");',
'    $("library-playlists-panel").classList.toggle("hidden", btn.dataset.tab !== "playlists");',
'  });',
'});',

'audio.addEventListener("play", updateNowPlaying);',
'audio.addEventListener("pause", updateNowPlaying);',
'audio.addEventListener("loadedmetadata", updateNowPlaying);',
'audio.addEventListener("timeupdate", updateNowPlaying);',
'audio.addEventListener("ended", function () {',
'  if (state.repeat && state.currentIndex >= 0 && !state.shuffle) playTrack(state.currentIndex);',
'  else nextTrack();',
'});',

'/* ---------- Upload ---------- */',
'var ITUNES_LOOKUP_ENABLED = true;',

'function xhrUpload(url, blob, contentType, onProgress) {',
'  return new Promise(function (resolve, reject) {',
'    var xhr = new XMLHttpRequest();',
'    xhr.open("PUT", url);',
'    if (contentType) xhr.setRequestHeader("Content-Type", contentType);',
'    xhr.upload.addEventListener("progress", function (e) {',
'      if (e.lengthComputable && onProgress) onProgress(e.loaded / e.total);',
'    });',
'    xhr.onload = function () {',
'      if (xhr.status >= 200 && xhr.status < 300) resolve(); else reject(new Error("HTTP " + xhr.status));',
'    };',
'    xhr.onerror = function () { reject(new Error("network error")); };',
'    xhr.send(blob);',
'  });',
'}',

'async function parseTags(file) {',
'  try {',
'    var mm = await import("https://esm.sh/music-metadata-browser@2.5.10?bundle");',
'    var meta = await mm.parseBlob(file);',
'    var common = meta.common || {};',
'    var picture = common.picture && common.picture[0];',
'    return {',
'      title: common.title || null,',
'      artist: common.artist || (common.artists && common.artists[0]) || null,',
'      album: common.album || null,',
'      album_artist: common.albumartist || null,',
'      year: common.year || null,',
'      genre: (common.genre && common.genre[0]) || null,',
'      track_number: (common.track && common.track.no) || null,',
'      disc_number: (common.disk && common.disk.no) || null,',
'      duration_seconds: meta.format && meta.format.duration ? Math.round(meta.format.duration) : null,',
'      cover: picture ? new Blob([picture.data], { type: picture.format || "image/jpeg" }) : null',
'    };',
'  } catch (e) {',
'    console.warn("tag parsing unavailable", e);',
'    return null;',
'  }',
'}',

'async function fetchFallbackCover(artist, title) {',
'  try {',
'    var q = encodeURIComponent((artist || "") + " " + (title || ""));',
'    var res = await fetch("https://itunes.apple.com/search?media=music&limit=1&term=" + q);',
'    if (!res.ok) return null;',
'    var data = await res.json();',
'    var item = data.results && data.results[0];',
'    if (!item || !item.artworkUrl100) return null;',
'    var url = item.artworkUrl100.replace("100x100bb", "600x600bb");',
'    var imgRes = await fetch(url);',
'    if (!imgRes.ok) return null;',
'    return await imgRes.blob();',
'  } catch (e) { return null; }',
'}',

'function addUploadRow(name) {',
'  var row = document.createElement("div");',
'  row.className = "upload-item";',
'  var top = document.createElement("div");',
'  top.className = "upload-item-top";',
'  var nameEl = document.createElement("span");',
'  nameEl.className = "upload-item-name";',
'  nameEl.textContent = name;',
'  var statusEl = document.createElement("span");',
'  statusEl.className = "upload-item-status";',
'  statusEl.textContent = "\u041f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0430\u2026";',
'  top.appendChild(nameEl);',
'  top.appendChild(statusEl);',
'  var bar = document.createElement("div");',
'  bar.className = "upload-bar";',
'  var fill = document.createElement("div");',
'  fill.className = "upload-bar-fill";',
'  bar.appendChild(fill);',
'  row.appendChild(top);',
'  row.appendChild(bar);',
'  $("upload-queue").appendChild(row);',
'  return {',
'    setStatus: function (text, cls) {',
'      statusEl.textContent = text;',
'      statusEl.className = "upload-item-status" + (cls ? " " + cls : "");',
'    },',
'    setProgress: function (pct) { fill.style.width = Math.round(pct * 100) + "%"; },',
'    remove: function () { row.remove(); }',
'  };',
'}',

'async function uploadOneFile(file) {',
'  var ui = addUploadRow(file.name);',
'  try {',
'    ui.setStatus("\u0427\u0442\u0435\u043d\u0438\u0435 \u0442\u0435\u0433\u043e\u0432\u2026");',
'    var tags = ITUNES_LOOKUP_ENABLED ? await parseTags(file) : null;',
'    var ext = (file.name.split(".").pop() || "mp3").toLowerCase();',
'    var title = (tags && tags.title) || file.name.replace(/\\.[^.]+$/, "");',

'    ui.setStatus("\u0421\u043e\u0437\u0434\u0430\u043d\u0438\u0435 \u0437\u0430\u043f\u0438\u0441\u0438\u2026");',
'    var createRes = await fetch("/api/tracks", {',
'      method: "POST",',
'      headers: { "Content-Type": "application/json" },',
'      body: JSON.stringify({',
'        title: title,',
'        artist: tags && tags.artist,',
'        album: tags && tags.album,',
'        album_artist: tags && tags.album_artist,',
'        year: tags && tags.year,',
'        genre: tags && tags.genre,',
'        track_number: tags && tags.track_number,',
'        disc_number: tags && tags.disc_number,',
'        duration_seconds: tags && tags.duration_seconds,',
'        mime_type: file.type || "audio/mpeg",',
'        file_size: file.size,',
'        file_extension: ext',
'      })',
'    });',
'    if (!createRes.ok) throw new Error("create failed");',
'    var created = await createRes.json();',

'    ui.setStatus("\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430\u2026");',
'    await xhrUpload(created.upload_url, file, file.type || "audio/mpeg", function (p) { ui.setProgress(p); });',

'    var coverBlob = (tags && tags.cover) || null;',
'    if (!coverBlob) coverBlob = await fetchFallbackCover(tags && tags.artist, title);',
'    if (coverBlob) {',
'      ui.setStatus("\u041e\u0431\u043b\u043e\u0436\u043a\u0430\u2026");',
'      await xhrUpload("/api/tracks/" + created.id + "/cover", coverBlob, coverBlob.type || "image/jpeg", function () {});',
'    }',

'    ui.setProgress(1);',
'    ui.setStatus("\u0413\u043e\u0442\u043e\u0432\u043e", "done");',
'    setTimeout(function () { ui.remove(); }, 2200);',
'  } catch (err) {',
'    console.error(err);',
'    ui.setStatus("\u041e\u0448\u0438\u0431\u043a\u0430", "error");',
'  }',
'}',

'async function handleFiles(fileList) {',
'  var files = Array.prototype.filter.call(fileList, function (f) { return f.type.indexOf("audio") === 0 || /\\.(mp3|flac|m4a|wav|ogg|aac|alac)$/i.test(f.name); });',
'  if (!files.length) return;',
'  for (var i = 0; i < files.length; i++) { await uploadOneFile(files[i]); }',
'  await loadTracks();',
'  toast(files.length > 1 ? "\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043d\u043e \u0442\u0440\u0435\u043a\u043e\u0432: " + files.length : "\u0422\u0440\u0435\u043a \u0437\u0430\u0433\u0440\u0443\u0436\u0435\u043d");',
'}',

'$("upload-file-input").addEventListener("change", function () {',
'  handleFiles(this.files);',
'  this.value = "";',
'});',

'var dropZone = $("drop-zone");',
'dropZone.addEventListener("click", function () { $("upload-file-input").click(); });',
'["dragenter", "dragover"].forEach(function (evt) {',
'  dropZone.addEventListener(evt, function (e) { e.preventDefault(); dropZone.classList.add("drag-over"); });',
'});',
'["dragleave", "drop"].forEach(function (evt) {',
'  dropZone.addEventListener(evt, function (e) { e.preventDefault(); dropZone.classList.remove("drag-over"); });',
'});',
'dropZone.addEventListener("drop", function (e) {',
'  if (e.dataTransfer && e.dataTransfer.files) handleFiles(e.dataTransfer.files);',
'});',

'/* ---------- Admin ---------- */',
'async function loadUsers() {',
'  var res = await fetch("/api/users");',
'  if (!res.ok) return;',
'  var data = await res.json();',
'  var container = $("users-list");',
'  container.replaceChildren();',
'  (data.users || []).forEach(function (user) {',
'    var row = document.createElement("div");',
'    row.className = "admin-user";',
'    var info = document.createElement("div");',
'    var name = document.createElement("div");',
'    name.className = "admin-user-name";',
'    name.textContent = user.username;',
'    var role = document.createElement("div");',
'    role.className = "admin-user-role";',
'    role.textContent = user.role === "admin" ? "\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440" : "\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c";',
'    info.appendChild(name);',
'    info.appendChild(role);',
'    row.appendChild(info);',
'    if (user.username !== state.user.username) {',
'      var button = document.createElement("button");',
'      button.innerHTML = ICONS.trash;',
'      button.addEventListener("click", function () { deleteUser(user.id); });',
'      row.appendChild(button);',
'    }',
'    container.appendChild(row);',
'  });',
'}',

'$("create-user-form").addEventListener("submit", async function (e) {',
'  e.preventDefault();',
'  var res = await fetch("/api/users", {',
'    method: "POST",',
'    headers: { "Content-Type": "application/json" },',
'    body: JSON.stringify({',
'      username: $("new-username").value.trim(),',
'      password: $("new-password").value,',
'      role: $("new-role").value',
'    })',
'  });',
'  if (res.ok) {',
'    $("create-user-form").reset();',
'    toast("\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c \u0441\u043e\u0437\u0434\u0430\u043d");',
'    loadUsers();',
'  } else {',
'    var data = await res.json().catch(function () { return {}; });',
'    toast(data.error || "\u041e\u0448\u0438\u0431\u043a\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f");',
'  }',
'});',

'async function deleteUser(id) {',
'  if (!confirm("\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f? \u0412\u0441\u0435 \u0435\u0433\u043e \u0442\u0440\u0435\u043a\u0438 \u0431\u0443\u0434\u0443\u0442 \u0443\u0434\u0430\u043b\u0435\u043d\u044b.")) return;',
'  var res = await fetch("/api/users/" + encodeURIComponent(id), { method: "DELETE" });',
'  if (res.ok) loadUsers(); else toast("\u041e\u0448\u0438\u0431\u043a\u0430 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f");',
'}',

'/* ---------- Service worker ---------- */',
'if ("serviceWorker" in navigator) {',
'  window.addEventListener("load", function () {',
'    navigator.serviceWorker.register("/sw.js").catch(function () {});',
'  });',
'}',

'setupMediaSession();',
'checkAuth();'
].join('\n');
