// Regenerates src/ui/icon-assets.ts from scripts/logo.svg -- the one place
// the app icon is actually drawn. Run after editing that file:
//   npm run build:icons
//
// Emits:
//   - APP_LOGO_SVG: the source SVG verbatim, served at GET /icon.svg
//   - ICON_PNG_{32,180,192,512}: rasterized PNGs (base64) for the browser
//     favicon, apple-touch-icon, and manifest.webmanifest icons
import sharp from 'sharp';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const svgPath = path.join(__dirname, 'logo.svg');
const outFile = path.join(__dirname, '..', 'src', 'ui', 'icon-assets.ts');

const svg = (await readFile(svgPath, 'utf8')).trim();
const sizes = [32, 180, 192, 512];

const pngs = {};
for (const size of sizes) {
  const buf = await sharp(Buffer.from(svg)).resize(size, size).png().toBuffer();
  pngs[size] = buf.toString('base64');
}

const source = `// AUTO-GENERATED by scripts/build-icons.mjs from scripts/logo.svg -- do not
// edit by hand. Regenerate with: npm run build:icons

export const APP_LOGO_SVG = ${JSON.stringify(svg)};

// Pre-rendered PNG app icons (base64), used for the favicon, apple-touch-icon,
// and manifest.webmanifest icons.
export const ICON_PNG_32 = "${pngs[32]}";
export const ICON_PNG_180 = "${pngs[180]}";
export const ICON_PNG_192 = "${pngs[192]}";
export const ICON_PNG_512 = "${pngs[512]}";
`;

await writeFile(outFile, source);
console.log(`Wrote ${outFile}`);
