// Regenerates src/ui/icon-assets.ts from scripts/logo.svg -- the one place
// the app icon is actually drawn. Run after editing that file:
//   npm run build:icons
//
// Emits:
//   - APP_LOGO_SVG: the source SVG verbatim, served at GET /icon.svg
//   - ICON_PNG_{32,180,192,512}: rasterized PNGs (base64) for the browser
//     favicon, apple-touch-icon, and manifest.webmanifest icons
//   - ICON_ASSET_VERSION: short hash of the above, appended as ?v=... to
//     every icon URL referenced from HTML/the manifest. The PNG/SVG routes
//     are served with a year-long immutable Cache-Control (see index.ts),
//     which only actually works if the URL changes whenever the content
//     does -- otherwise browsers, Cloudflare's own edge cache, and iOS's
//     famously sticky apple-touch-icon caching all keep serving the old
//     bytes at the old URL indefinitely, exactly what happened the first
//     time this icon was replaced without a version query.
import sharp from 'sharp';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const svgPath = path.join(__dirname, 'logo.svg');
const outFile = path.join(__dirname, '..', 'src', 'ui', 'icon-assets.ts');

const svg = (await readFile(svgPath, 'utf8')).trim();
const sizes = [32, 180, 192, 512];

const pngs = {};
for (const size of sizes) {
  const buf = await sharp(Buffer.from(svg)).resize(size, size).png().toBuffer();
  pngs[size] = buf.toString('base64');
}

const version = createHash('sha256')
  .update(svg + sizes.map((s) => pngs[s]).join(''))
  .digest('hex')
  .slice(0, 10);

const source = `// AUTO-GENERATED by scripts/build-icons.mjs from scripts/logo.svg -- do not
// edit by hand. Regenerate with: npm run build:icons

export const APP_LOGO_SVG = ${JSON.stringify(svg)};

// Pre-rendered PNG app icons (base64), used for the favicon, apple-touch-icon,
// and manifest.webmanifest icons.
export const ICON_PNG_32 = "${pngs[32]}";
export const ICON_PNG_180 = "${pngs[180]}";
export const ICON_PNG_192 = "${pngs[192]}";
export const ICON_PNG_512 = "${pngs[512]}";

// Content hash of the above -- append as ?v=\${ICON_ASSET_VERSION} to every
// icon URL so a changed icon actually reaches browsers/CDN/iOS. See the
// comment at the top of this script for why that matters.
export const ICON_ASSET_VERSION = "${version}";
`;

await writeFile(outFile, source);
console.log(`Wrote ${outFile} (version ${version})`);
